---
- name: Verify init role works when installing recommended packages
  hosts: all
  gather_facts: false
  roles:
    - role: community.openwrt.init
      vars:
        openwrt_install_recommended_packages: false
