---
driver:
  name: docker
platforms:
  - name: openwrt_x86_64-${OPENWRT_VERSION:-24.10.4}
    image: openwrt/rootfs:x86_64-${OPENWRT_VERSION:-24.10.4}
    command: sh -c "mkdir -p /var/lock; sleep infinity"
    pre_build_image: true
scenario:
  test_sequence:
    - create
    - converge
    - destroy
