---
# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: community
name: openwrt
version: 0.5.0
readme: README.md
authors:
  - Alexei Znamensky (github.com/russoz)
description: >-
  The community.openwrt collection enables management of OpenWrt devices
  without Python installed by using shell-based modules.
license_file: LICENSE
tags:
  - openwrt
  - networking
  - router
repository: https://github.com/ansible-collections/community.openwrt
documentation: https://ansible-collections.github.io/community.openwrt/branch/main/
homepage: https://github.com/ansible-collections/community.openwrt
issues: https://github.com/ansible-collections/community.openwrt/issues

build_ignore:
  - changelogs/.plugin-cache.yaml
  - extensions/
  - Pipfile*
  - .*
  - AI
