# Copyright (c) 2026, Alexei Znamensky (@russoz)
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

driver:
  name: docker
platforms:
  - name: openwrt_x86_64-${OPENWRT_VERSION:-24.10.4}
    image: openwrt/rootfs:x86_64-${OPENWRT_VERSION:-24.10.4}
    command: /sbin/init
    pre_build_image: true
scenario:
  test_sequence:
    - dependency
    - create
    - converge
    - destroy
