# Copyright (c) 2025, Alexei Znamensky (@russoz)
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Run module-specific role provided by TEST_TARGET_ROLE
      include_role:
        name: "{{ lookup('env', 'TEST_TARGET_ROLE') }}"
