# Copyright (c) 2025, Alexei Znamensky (@russoz)
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

driver:
  name: docker
platforms:
  - name: openwrt_x86_64-24.10.4
    image: openwrt/rootfs:x86_64-24.10.4
    command: sh -c "mkdir -p /var/lock; sleep infinity"
    pre_build_image: true
  - name: openwrt_x86_64-23.05.6
    image: openwrt/rootfs:x86_64-23.05.6
    command: sh -c "mkdir -p /var/lock; sleep infinity"
    pre_build_image: true
  - name: openwrt_x86_64-22.03.7
    image: openwrt/rootfs:x86_64-22.03.7
    command: sh -c "mkdir -p /var/lock; sleep infinity"
    pre_build_image: true
  - name: openwrt_x86_64-21.02.7
    image: openwrt/rootfs:x86_64-21.02.7
    command: sh -c "mkdir -p /var/lock; sleep infinity"
    pre_build_image: true
scenario:
  test_sequence:
    - create
    - converge
    - destroy

# Ensure generated ansible.cfg allows legacy/broken conditionals used by some drivers
provisioner:
  name: ansible
  config_options:
    defaults:
      allow_broken_conditionals: True
